# Generated by Django 3.1.7 on 2021-04-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstripedetails',
            name='customer_id',
            field=models.CharField(default='nodetails', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectstripedetails',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
