# Generated by Django 3.1.7 on 2021-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20210423_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptiondetails',
            name='default_street_address2',
            field=models.CharField(blank=True, default=' ', max_length=80, verbose_name='Street Address 2'),
        ),
    ]
