# Generated by Django 3.1.7 on 2021-04-04 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_name', models.CharField(max_length=50, verbose_name='Change Name')),
                ('change_status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('WiP', 'Work in Progress'), ('R', 'Rejected')], max_length=20, verbose_name='Change Status')),
                ('change_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Change Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='Project Name')),
                ('original_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Estimate/Budget')),
                ('has_subscription', models.BooleanField(blank=True, default=False, null=True)),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_permission', models.CharField(choices=[('Edit', 'Edit'), ('View', 'View')], max_length=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
                ('project_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_StripeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_sub', models.CharField(max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='change/attachments/')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.change')),
            ],
        ),
        migrations.AddField(
            model_name='change',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
        migrations.AddField(
            model_name='change',
            name='project_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
