# Generated by Django 3.1.7 on 2021-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='change_cost',
            field=models.FloatField(default=0, verbose_name='Change Cost'),
        ),
        migrations.AlterField(
            model_name='change',
            name='change_name',
            field=models.CharField(max_length=40, verbose_name='Change Name'),
        ),
    ]
