# Generated by Django 3.1.7 on 2021-03-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='original_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
