# Generated by Django 3.1.7 on 2021-04-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeattachments',
            name='change',
        ),
        migrations.AddField(
            model_name='change',
            name='attachment',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='dashboard.ChangeAttachments'),
        ),
    ]
