# Generated by Django 3.1.7 on 2021-03-24 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_project_original_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_name', models.CharField(max_length=50, verbose_name='Change Name')),
                ('change_status', models.CharField(choices=[('Accepted', 'A'), ('Pending', 'P'), ('Work in Progress', 'WiP'), ('Rejected', 'R')], max_length=20, verbose_name='Change Status')),
                ('change_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
                ('project_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
