# Generated by Django 3.1.7 on 2021-03-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='project',
            new_name='project_id',
        ),
        migrations.AlterField(
            model_name='change',
            name='change_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Change Cost'),
        ),
    ]
