# Generated by Django 3.1.7 on 2021-04-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('payments', '0002_auto_20210411_1358'),
        ('dashboard', '0004_delete_project_stripedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='project_user',
        ),
        migrations.AlterField(
            model_name='change',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
