# Generated by Django 3.1.7 on 2021-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210327_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_subscription',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='original_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Estimate/Budget'),
        ),
    ]
